# Generated by Django 6.1 on 2026-08-18 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('short_description', models.CharField(help_text='Brief description shown in cards', max_length=300)),
                ('description', models.TextField(help_text='Full program description')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='academics/programs/')),
                ('duration', models.CharField(blank=True, help_text='e.g., 2 Years', max_length=100)),
                ('eligibility', models.TextField(blank=True, help_text='Eligibility criteria for this program')),
                ('icon', models.CharField(blank=True, help_text='Heroicon name (e.g., academic-cap)', max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower number appears first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Program',
                'verbose_name_plural': 'Academic Programs',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Mid-Term Examination 2083', max_length=200)),
                ('academic_year', models.CharField(help_text='e.g., 2082/83', max_length=20)),
                ('grade', models.CharField(help_text='e.g., Grade 11, Grade 12, All Grades', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['-start_date'], name='academics_e_start_d_bdf844_idx'), models.Index(fields=['academic_year'], name='academics_e_academi_962e99_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExamRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=50)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, help_text='Exam room or hall', max_length=100)),
                ('remarks', models.CharField(blank=True, help_text='Additional notes', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='academics.exam')),
            ],
            options={
                'verbose_name': 'Exam Routine',
                'verbose_name_plural': 'Exam Routines',
                'ordering': ['exam_date', 'start_time'],
                'indexes': [models.Index(fields=['exam_date'], name='academics_e_exam_da_3d234c_idx'), models.Index(fields=['exam', 'grade'], name='academics_e_exam_id_b61a64_idx')],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('symbol_number', models.CharField(db_index=True, help_text='Unique symbol number for result lookup', max_length=50)),
                ('grade', models.CharField(db_index=True, max_length=50)),
                ('roll_number', models.CharField(blank=True, max_length=50)),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('result_status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('ABSENT', 'Absent')], default='PASS', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.exam')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['symbol_number'], name='academics_r_symbol__0dd182_idx'), models.Index(fields=['exam', 'grade'], name='academics_r_exam_id_72573e_idx'), models.Index(fields=['is_published'], name='academics_r_is_publ_2de8bd_idx')],
                'unique_together': {('exam', 'symbol_number')},
            },
        ),
    ]
