# Generated by Django 6.1 on 2026-08-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examroutine',
            options={'ordering': ['grade', 'exam_date', 'start_time'], 'verbose_name': 'Exam Routine', 'verbose_name_plural': 'Exam Routines'},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='grade',
        ),
        migrations.AlterField(
            model_name='exam',
            name='academic_year',
            field=models.CharField(help_text='e.g., 2083/84', max_length=20),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(help_text='e.g., First Terminal Examination 2083', max_length=200),
        ),
        migrations.AlterField(
            model_name='examroutine',
            name='grade',
            field=models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], help_text='Select the class (Class 1 - Class 10)', max_length=2, verbose_name='Class'),
        ),
        migrations.AddIndex(
            model_name='examroutine',
            index=models.Index(fields=['grade'], name='academics_e_grade_1c41fb_idx'),
        ),
    ]
