# Generated by Django 6.1 on 2026-08-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_examroutine_options_remove_exam_grade_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='examroutine',
            constraint=models.UniqueConstraint(fields=('exam', 'grade', 'subject', 'exam_date', 'start_time'), name='unique_exam_routine'),
        ),
    ]
