# Generated by Django 6.1 on 2026-08-22 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_examroutine_unique_exam_routine'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='e.g., English, Mathematics, Science', max_length=200)),
                ('full_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum marks for this subject (optional)', max_digits=6, null=True)),
                ('obtained_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Marks obtained by the student in this subject', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.ForeignKey(help_text='The result (student/exam) these subject marks belong to', on_delete=django.db.models.deletion.CASCADE, related_name='subject_marks', to='academics.result')),
            ],
            options={
                'verbose_name': 'Subject Mark',
                'verbose_name_plural': 'Subject Marks',
                'ordering': ['subject'],
                'constraints': [models.UniqueConstraint(fields=('result', 'subject'), name='unique_result_subject_mark')],
            },
        ),
    ]
