# Generated by Django 6.1 on 2026-08-26 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_subjectmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated')], help_text='Type of action performed', max_length=20)),
                ('old_obtained_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Previous obtained marks (null on create)', max_digits=6, null=True)),
                ('new_obtained_marks', models.DecimalField(blank=True, decimal_places=2, help_text='New obtained marks', max_digits=6, null=True)),
                ('old_full_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Previous full marks (null on create)', max_digits=6, null=True)),
                ('new_full_marks', models.DecimalField(blank=True, decimal_places=2, help_text='New full marks', max_digits=6, null=True)),
                ('old_gpa', models.DecimalField(blank=True, decimal_places=2, help_text='Previous GPA', max_digits=4, null=True)),
                ('new_gpa', models.DecimalField(blank=True, decimal_places=2, help_text='New GPA', max_digits=4, null=True)),
                ('old_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Previous percentage', max_digits=5, null=True)),
                ('new_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='New percentage', max_digits=5, null=True)),
                ('old_result_status', models.CharField(blank=True, help_text='Previous result status', max_length=10, null=True)),
                ('new_result_status', models.CharField(blank=True, help_text='New result status', max_length=10, null=True)),
                ('subject_name', models.CharField(blank=True, help_text='Subject name at time of change', max_length=200)),
                ('student_name', models.CharField(blank=True, help_text='Student name at time of change', max_length=200)),
                ('symbol_number', models.CharField(blank=True, help_text='Symbol number at time of change', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the change')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(help_text='The result this audit entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='academics.result')),
                ('subject_mark', models.ForeignKey(blank=True, help_text='The subject mark that was changed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='academics.subjectmark')),
            ],
            options={
                'verbose_name': 'Marks Audit Log',
                'verbose_name_plural': 'Marks Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['result', '-created_at'], name='academics_m_result__3dbdf2_idx'), models.Index(fields=['changed_by'], name='academics_m_changed_537bba_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10')], help_text='Class the teacher is assigned to', max_length=2)),
                ('subject', models.CharField(help_text='Subject the teacher is authorized for', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The teacher (Django user)', on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Subject Assignment',
                'verbose_name_plural': 'Teacher Subject Assignments',
                'indexes': [models.Index(fields=['user', 'grade'], name='academics_t_user_id_b517a2_idx')],
                'unique_together': {('user', 'grade', 'subject')},
            },
        ),
    ]
