# Generated by Django 6.1 on 2026-08-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image to display with the notice', null=True, upload_to='notices/images/'),
        ),
    ]
