# Generated by Django 6.1 on 2026-08-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Amity College', max_length=200)),
                ('organization_name', models.CharField(default='Amity Education Foundation', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Upload school logo (recommended: PNG with transparent background)', null=True, upload_to='school/logo/')),
                ('favicon', models.ImageField(blank=True, help_text='Upload favicon (recommended: 32x32 PNG)', null=True, upload_to='school/favicon/')),
                ('address', models.TextField(default='Amity Higher Secondary School, 123 Amity Road, Birtamod 57204, Nepal')),
                ('phone', models.CharField(default='023-542762', max_length=50)),
                ('email', models.EmailField(default='info@amity.edu.np', max_length=254)),
                ('website', models.URLField(blank=True, default='https://www.amity.edu.np')),
                ('principal_name', models.CharField(blank=True, default='', help_text="Principal's full name", max_length=200)),
                ('principal_message', models.TextField(blank=True, default='', help_text='Message from the principal')),
                ('principal_photo', models.ImageField(blank=True, null=True, upload_to='school/principal/')),
                ('about', models.TextField(blank=True, default='Amity College, established under the Amity Education Foundation, is a leading educational institution in Birtamod, Nepal. We are committed to providing quality education and nurturing the holistic development of our students.', help_text='About the school')),
                ('mission', models.TextField(blank=True, default='To provide quality education that empowers students to achieve academic excellence, develop critical thinking skills, and become responsible citizens of Nepal and the world.', help_text='School mission statement')),
                ('vision', models.TextField(blank=True, default='To be the premier educational institution in Eastern Nepal, recognized for academic excellence, innovation, and character development.', help_text='School vision statement')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('admission_open', models.BooleanField(default=True, help_text='Toggle admission open/closed status')),
                ('admission_info', models.TextField(blank=True, default='Admissions are now open for the academic year 2082/83. Apply now to secure your spot.', help_text='Admission information displayed on website')),
                ('hero_title', models.CharField(default='Empowering Students to Learn, Lead and Succeed', help_text='Main hero section headline', max_length=200)),
                ('hero_subtitle', models.TextField(default='Amity College, Birtamod provides a world-class education rooted in Nepali values. Join our community of learners and build your future with us.', help_text='Hero section subheading')),
                ('hero_image', models.ImageField(blank=True, help_text='Main hero background image (recommended: 1920x1080)', null=True, upload_to='school/hero/')),
                ('established_year', models.CharField(blank=True, default='', help_text='Year the school was established', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
    ]
